RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = bbi2c tcm8230

WR_DRIVERS = kernel

TARGET = camera.bin

SRC = camera.c

include ../../boards/camera/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


