RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = bbi2c usb_cdc

PERIPHERALS = extint

WR_DRIVERS = kernel

TARGET = i2cs_test1.bin

SRC = i2cs_test1.c

include ../../boards/camera/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


