RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = bbi2c tcm8230

PERIPHERALS = extint

WR_DRIVERS = kernel usb_logging

TARGET = camera_i2c.bin

SRC = camera_i2c.c

include ../../boards/camera/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


