RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = bbi2c pacer

TARGET = i2cm_test2.bin

SRC = i2cm_test2.c

include ../../boards/camera/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


