RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = bbi2c

PERIPHERALS = extint

WR_DRIVERS = kernel usb_logging steering motor

TARGET = motor_i2c.bin

SRC = motor_i2c.c

include ../../boards/motor/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


