RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

DRIVERS = busart

WR_DRIVERS = kernel

TARGET = comms.bin

SRC = comms.c

include ../../boards/comms/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk


