RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

WRLIB_DIR = ../../wrlib

PERIPHERALS = 

DRIVERS = bbi2c

WR_DRIVERS = kernel bluetooth

TARGET = comms.bin

SRC = comms.c

include ../../boards/comms/board.mk
include $(WRLIB_DIR)/wrlib.mk
include $(MMCULIB_DIR)/mmculib.mk

